title: "Kipyo Kim"
email: your-email@example.com
description: >-
  AI Researcher & Undergraduate Student.
  Interested in Machine Learning, Computer Vision, and NLP.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - publications.md
  - projects.md
  - cv.md
